_wandb:
    value:
        cli_version: 0.22.0
        e:
            4ivg1wa2a22k5vs35n0cey3d1tytmmyd:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "254634999808"
                        used: "246074851328"
                email: adey004azeez@gmail.com
                executable: C:\Users\USER\anaconda3\python.exe
                git:
                    commit: bc46b3d83a176394dfcd4566dc1c2d9005c62531
                    remote: https://github.com/Adeyemi-authentic/Football-match-project.git
                host: DESKTOP-O1H15VD
                memory:
                    total: "8464732160"
                os: Windows-10-10.0.19045-SP0
                program: PycharmProjects/deply/ALL league prediction with pytorch and wandb.ipynb
                python: CPython 3.11.5
                root: C:\Users\USER\PycharmProjects\deply
                startedAt: "2025-10-07T18:56:04.957451Z"
                writerId: 4ivg1wa2a22k5vs35n0cey3d1tytmmyd
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
            "4": 3.11.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
dropout_prob:
    value: 0.24533501695304957
hidden_size:
    value: 32
learning_rate:
    value: 0.010876241016945553
num_epochs:
    value: 750
