_wandb:
    value:
        cli_version: 0.22.0
        e:
            5q1nfgo6bp8dn5m0yn6hs1oz0y9tcs2a:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "254634999808"
                        used: "246075068416"
                email: adey004azeez@gmail.com
                executable: C:\Users\USER\anaconda3\python.exe
                git:
                    commit: bc46b3d83a176394dfcd4566dc1c2d9005c62531
                    remote: https://github.com/Adeyemi-authentic/Football-match-project.git
                host: DESKTOP-O1H15VD
                memory:
                    total: "8464732160"
                os: Windows-10-10.0.19045-SP0
                program: PycharmProjects/deply/ALL league prediction with pytorch and wandb.ipynb
                python: CPython 3.11.5
                root: C:\Users\USER\PycharmProjects\deply
                startedAt: "2025-10-07T18:56:26.101471Z"
                writerId: 5q1nfgo6bp8dn5m0yn6hs1oz0y9tcs2a
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 14
            "4": 3.11.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
dropout_prob:
    value: 0.39816770668513385
hidden_size:
    value: 56
learning_rate:
    value: 0.01821717993587923
num_epochs:
    value: 1000
