_wandb:
    value:
        cli_version: 0.22.0
        e:
            mfcd9epdyvp3hrq2qf71dy7t27d4zjpk:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "254634999808"
                        used: "245786304512"
                email: adey004azeez@gmail.com
                executable: C:\Users\USER\anaconda3\python.exe
                git:
                    commit: bc46b3d83a176394dfcd4566dc1c2d9005c62531
                    remote: https://github.com/Adeyemi-authentic/Football-match-project.git
                host: DESKTOP-O1H15VD
                memory:
                    total: "8464732160"
                os: Windows-10-10.0.19045-SP0
                program: PycharmProjects/deply/ALL league prediction with pytorch and wandb.ipynb
                python: CPython 3.11.5
                root: C:\Users\USER\PycharmProjects\deply
                startedAt: "2025-10-07T18:42:24.878971Z"
                writerId: mfcd9epdyvp3hrq2qf71dy7t27d4zjpk
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.11.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
dropout_prob:
    value: 0.25803221172767593
hidden_size:
    value: 42
learning_rate:
    value: 0.014850395661032589
num_epochs:
    value: 1000
