_wandb:
    value:
        cli_version: 0.22.0
        e:
            to4nf8cdoe450ecujg2eu763j79c2ed5:
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "254634999808"
                        used: "245772087296"
                email: adey004azeez@gmail.com
                executable: C:\Users\USER\anaconda3\python.exe
                git:
                    commit: bc46b3d83a176394dfcd4566dc1c2d9005c62531
                    remote: https://github.com/Adeyemi-authentic/Football-match-project.git
                host: DESKTOP-O1H15VD
                memory:
                    total: "8464732160"
                os: Windows-10-10.0.19045-SP0
                program: PycharmProjects/deply/ALL league prediction with pytorch and wandb.ipynb
                python: CPython 3.11.5
                root: C:\Users\USER\PycharmProjects\deply
                startedAt: "2025-10-07T18:41:26.515431Z"
                writerId: to4nf8cdoe450ecujg2eu763j79c2ed5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.11.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
dropout_prob:
    value: 0.27155186314608276
hidden_size:
    value: 32
learning_rate:
    value: 0.01262555093792994
num_epochs:
    value: 750
